version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py makemigrations core &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      - SECRET_KEY=django-insecure-&*)838bj5l=f*gx*wg5hk!)u)8qy+_(kru74si1ockw*rt-n2^
      - DEBUG=1
    depends_on:
      - db
    tty: true

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword # should later be replaced by an encrypted variable
