version: '3.7'

services:
  web:
    build: .
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
    expose:
      - 8000
    env_file: .env.prod
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file: .env.db.prod
volumes:
  static_volume:
