version: '3.7'

services:
  web:
    build: .
    command: gunicorn app.wsgi --bind 0.0.0.0:$PORT
    volumes:
      - static_volume:/app/static
      - media_volume:/vol/web/media/
    expose:
      - $PORT
    env_file: .env.prod
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    volumes:
      - db_data_volume:/var/lib/postgresql/data
    env_file: .env.db.prod

volumes:
  static_volume:
  media_volume:
  db_data_volume:
