# Generated by Django 3.1.8 on 2021-04-23 20:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.movie_image_file_path),
        ),
    ]
