# Generated by Django 3.1.8 on 2021-04-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rental_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rental',
            name='daily_rental_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
