# Generated by Django 3.1.8 on 2021-04-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedmovie',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
