# Generated by Django 3.1.14 on 2023-05-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='daily_rental_fee',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
