# Generated by Django 3.1.14 on 2023-05-20 19:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230520_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='daily_rental_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
