# Generated by Django 3.1.14 on 2023-05-22 01:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230520_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rental_debt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
