# Generated by Django 3.1.8 on 2021-04-27 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210426_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='rental_debt',
        ),
    ]
