# Generated by Django 3.1.8 on 2021-04-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210425_2206'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rental',
            unique_together={('user', 'movie')},
        ),
    ]
