# Generated by Django 3.1.8 on 2021-04-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_rental_rental_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedmovie',
            name='liked',
        ),
    ]
