# Generated by Django 3.1.8 on 2021-04-26 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_purchased'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchased',
            new_name='Purchase',
        ),
    ]
