# Generated by Django 3.1.8 on 2021-04-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210426_0110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rental',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('user', 'movie', 'date_bought'), name='unique movie bought'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.UniqueConstraint(fields=('user', 'movie', 'date_returned'), name='unique movie returned'),
        ),
    ]
